export const APP_NAME = 'Tablero Operativo'

/** Rutas según módulos de lovable-spec §5 */
export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  DASHBOARD_KPIS: '/dashboard/kpis',
  DASHBOARD_GAPS: '/dashboard/gaps',
  KANBAN: '/kanban',
  DISCIPLINA: '/disciplina',
  AREAS: '/areas',
  CALENDARIO: '/calendario',
  REPORTES: '/reportes',
  NOTIFICACIONES: '/notificaciones',
  DISTANCIAS: '/distancias',
  ACADEMIA: '/academia',
  MANUAL: '/manual',
  SETTINGS: '/settings',
  SETTINGS_PROFILE: '/settings/profile',
  SETTINGS_DISTANCIAS: '/settings/distancias',
  SETTINGS_USERS: '/settings/users',
  SETTINGS_USERS_DETAIL: '/settings/users/:id',
  SETTINGS_CATALOGS: '/settings/catalogs',
  SETTINGS_CATALOGS_ROLES: '/settings/catalogs/roles',
  SETTINGS_CATALOGS_AREAS: '/settings/catalogs/areas',
  SETTINGS_CATALOGS_STATUSES: '/settings/catalogs/statuses',
  SETTINGS_CATALOGS_PRIORITIES: '/settings/catalogs/priorities',
  SETTINGS_CATALOGS_DROPDOWNS: '/settings/catalogs/dropdowns',
  SETTINGS_CATALOGS_DROPDOWNS_OPTIONS: '/settings/catalogs/dropdowns/:catalogId',
  SETTINGS_CATALOGS_KPIS: '/settings/catalogs/kpis',
  SETTINGS_CATALOGS_GAPS: '/settings/catalogs/gaps',
  SETTINGS_CATALOGS_ORIGINS: '/settings/catalogs/origins',
  SETTINGS_CATALOGS_DESTINATIONS: '/settings/catalogs/destinations',
  SETTINGS_CATALOGS_SOLICITUDES_GUARDADAS: '/settings/catalogs/solicitudes-guardadas',
} as const
