-- =============================================================================
-- Academia O2C: modulos configurables por super admin.
-- Los 8 modulos base siguen en codigo; esta tabla agrega modulos nuevos.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.academy_modules (
  id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 9) PRIMARY KEY,
  title text NOT NULL,
  subtitle text NOT NULL DEFAULT '',
  duration text NOT NULL DEFAULT '1 hora',
  pdf_name text NOT NULL,
  objectives text[] NOT NULL DEFAULT '{}',
  concepts jsonb NOT NULL DEFAULT '[]'::jsonb,
  steps text[] NOT NULL DEFAULT '{}',
  exercise text NOT NULL DEFAULT '',
  deliverable text NOT NULL DEFAULT '',
  quiz jsonb NOT NULL DEFAULT '[]'::jsonb,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES public.usuarios(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_academy_modules_active_id ON public.academy_modules(is_active, id);

DROP TRIGGER IF EXISTS set_academy_modules_updated_at ON public.academy_modules;
CREATE TRIGGER set_academy_modules_updated_at
  BEFORE UPDATE ON public.academy_modules
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

ALTER TABLE public.academy_modules ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS academy_modules_select_authenticated ON public.academy_modules;
CREATE POLICY academy_modules_select_authenticated ON public.academy_modules
  FOR SELECT TO authenticated
  USING (is_active OR public.is_super_admin());

DROP POLICY IF EXISTS academy_modules_insert_super_admin ON public.academy_modules;
CREATE POLICY academy_modules_insert_super_admin ON public.academy_modules
  FOR INSERT TO authenticated
  WITH CHECK (public.is_super_admin() OR public.has_business_role('super_admin'));

DROP POLICY IF EXISTS academy_modules_update_super_admin ON public.academy_modules;
CREATE POLICY academy_modules_update_super_admin ON public.academy_modules
  FOR UPDATE TO authenticated
  USING (public.is_super_admin() OR public.has_business_role('super_admin'))
  WITH CHECK (public.is_super_admin() OR public.has_business_role('super_admin'));

DROP POLICY IF EXISTS academy_modules_delete_super_admin ON public.academy_modules;
CREATE POLICY academy_modules_delete_super_admin ON public.academy_modules
  FOR DELETE TO authenticated
  USING (public.is_super_admin() OR public.has_business_role('super_admin'));

COMMENT ON TABLE public.academy_modules IS 'Modulos adicionales de Academia O2C creados desde super admin.';

DROP POLICY IF EXISTS academia_insert ON storage.objects;
CREATE POLICY academia_insert ON storage.objects
  FOR INSERT TO authenticated
  WITH CHECK (
    bucket_id = 'academia'
    AND (
      public.is_app_admin()
      OR public.has_business_role('super_admin')
      OR EXISTS (
        SELECT 1 FROM public.usuarios u
        WHERE u.user_id = auth.uid()
          AND trim(u.rol) IN ('DG', 'Sistemas')
      )
    )
  );

DROP POLICY IF EXISTS academia_update ON storage.objects;
CREATE POLICY academia_update ON storage.objects
  FOR UPDATE TO authenticated
  USING (
    bucket_id = 'academia'
    AND (
      public.is_app_admin()
      OR public.has_business_role('super_admin')
      OR EXISTS (
        SELECT 1 FROM public.usuarios u
        WHERE u.user_id = auth.uid()
          AND trim(u.rol) IN ('DG', 'Sistemas')
      )
    )
  );

DROP POLICY IF EXISTS academia_delete ON storage.objects;
CREATE POLICY academia_delete ON storage.objects
  FOR DELETE TO authenticated
  USING (
    bucket_id = 'academia'
    AND (
      public.is_app_admin()
      OR public.has_business_role('super_admin')
      OR EXISTS (
        SELECT 1 FROM public.usuarios u
        WHERE u.user_id = auth.uid()
          AND trim(u.rol) IN ('DG', 'Sistemas')
      )
    )
  );
